# Dependencies
markdown:       redcarpet
highlights:     pygments

# Permalinks
permalink:      /blog/:categories/:year/:month/:day/:title

# Setup
title:          Screen Time
tagline:        Your Kids Will Hate It

baseurl:        http://screentime.io/
url:            http://screentime.io/

# Blog
paginate_path:    "blog/page:num"
paginate:         5

#
author:
  name:           Mark Otto
  url:            https://twitter.com/babybinks
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
google_analytics: UA-
timezone:           America/Chicago

